
// Auto-generated by AutoPilot on 14-08-2023 at 21:27:05

const express = require('express');
const router = express.Router();

//Route to get the 5 best Hindi Movies
router.get('/bestMovies', (req, res) => {
    const bestMovies = [
        '3 Idiots', 
        'PK', 
        'K3G', 
        'Dilwale Dulhania Le Jayenge', 
        'Andaz Apna Apna'
    ];

    //Return the 5 best Hindi Movies
    res.json(bestMovies);
});

module.exports = router;

//This is a router to get the 5 best Hindi movies. It is imported from express and the route '/bestMovies' is specified. The response is sent in JSON format with the 5 best Hindi movies.