
// Auto-generated by AutoPilot on 14-08-2023 at 21:12:40


const express = require('express');
const router = express.Router();

// Route to return yo
router.get('/yo', (req, res) => {
    // Send a response with yo
    res.send('yo');
});

module.exports = router;